name: structural_directives
description: Structural directives example
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha
  angular_forms: ^1.0.1-alpha

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

dependency_overrides:
  angular: ^5.0.0-alpha

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
