name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.1.1
  ngforms: ^4.1.1

dev_dependencies:
  ngtest: ^4.1.1
  build_runner: ^2.2.0
  build_test: ^2.1.5
  build_web_compilers: ^3.2.4
  ngpageloader: ^5.0.0
  test: ^1.21.0
