name: component_styles
description: Component Styles example
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4

dev_dependencies:
  browser: ^0.10.0
  build_runner: ^0.7.0
  build_test: ^0.9.4
  build_web_compilers: ^0.2.0

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
